### Задание 2

In [1]:
import pandas as pd

%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
data = pd.read_table("AUCs.txt")

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


In [3]:
data.head()

Unnamed: 0   C4.5  C4.5+m  C4.5+cf  C4.5+m+cf
0           adult (sample)  0.763   0.768    0.771      0.798
1            breast cancer  0.599   0.591    0.590      0.569
2  breast cancer wisconsin  0.954   0.971    0.968      0.967
3                      cmc  0.628   0.661    0.654      0.657
4               ionosphere  0.882   0.888    0.886      0.898

In [4]:
data.shape

(14, 5)

In [5]:
from itertools import combinations

In [7]:
for i in combinations([1,2,3,4],2):
    print(i)

(1, 2)
(1, 3)
(1, 4)
(2, 3)
(2, 4)
(3, 4)


In [8]:
import scipy.stats as stats

In [14]:
stats_list = []

for pair in combinations(["C4.5","C4.5+m", "C4.5+cf", "C4.5+m+cf"],2):
    stats_list.append([stats.wilcoxon(data[pair[0]] - data[pair[1]])[1], pair])

In [15]:
stats_list

[[0.01075713311978963, ('C4.5', 'C4.5+m')],
 [0.861262330095348, ('C4.5', 'C4.5+cf')],
 [0.015906444101703374, ('C4.5', 'C4.5+m+cf')],
 [0.046332729793395394, ('C4.5+m', 'C4.5+cf')],
 [0.3278256758446406, ('C4.5+m', 'C4.5+m+cf')],
 [0.022909099354356588, ('C4.5+cf', 'C4.5+m+cf')]]

### Задание 4

In [17]:
auc_diff = []

for name in ["C4.5+m", "C4.5+cf", "C4.5+m+cf"]:
    auc_diff.append((data['C4.5']-data[name]).mean())

In [18]:
auc_diff

[-0.015499999999999983, -0.003857142857142829, -0.022285714285714298]

### Задание 6

In [19]:
stats_list = np.asarray(stats_list)

In [20]:
stats_list[:,0]

array([0.01075713311978963, 0.861262330095348, 0.015906444101703374,
       0.046332729793395394, 0.3278256758446406, 0.022909099354356588],
      dtype=object)

In [22]:
from statsmodels.sandbox.stats.multicomp import multipletests 

In [23]:
reject, p_corrected, a1, a2 = multipletests(stats_list[:,0], 
                                            alpha = 0.05, 
                                            method = 'holm') 

In [24]:
p_corrected

array([0.06454279871873778, 0.861262330095348, 0.07953222050851687,
       0.13899818938018618, 0.6556513516892812, 0.09163639741742635],
      dtype=object)

### Задание 7

In [25]:
reject_bh, p_corrected_bh, a1_bh, a2_bh = multipletests(stats_list[:,0], 
                                            alpha = 0.05, 
                                            method = 'fdr_bh') 

In [26]:
p_corrected_bh

array([0.045818198708713176, 0.861262330095348, 0.045818198708713176,
       0.06949909469009309, 0.3933908110135687, 0.045818198708713176],
      dtype=object)